services:
  postgres:
    image: postgres
    container_name: django-assesement-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  data:
    driver: local
